name: Build and Push Docker Images

on:
  push:
    branches: [main]
    tags: [v*]

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push slim image
        uses: docker/build-push-action@v5
        with:
          context: .  # Explicit context
          file: Dockerfile.slim
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/${{ github.repository }}/dynamic-dns:slim
            ghcr.io/${{ github.repository }}/dynamic-dns:latest
          build-args: |
            BUILDKIT_INLINE_CACHE=1

      - name: Build and push distroless image
        uses: docker/build-push-action@v5
        with:
          context: .  # Explicit context
          file: Dockerfile.distroless
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/${{ github.repository }}/dynamic-dns:distroless
          build-args: |
            BUILDKIT_INLINE_CACHE=1

      - name: Scan images
        run: |
          docker scan ghcr.io/${{ github.repository }}/dynamic-dns:slim || true
          docker scan ghcr.io/${{ github.repository }}/dynamic-dns:distroless || true